### ISSUE TITLE
use in spring boot

### ISSUE THREAD

**Issue by MohsenK** [kwon37xi/jsp-template-inheritance#5]
Hi
I want to use this library on spring boot.
but i give some errors.

The absolute uri: http://kwonnam.pe.kr/jsp/template-inheritance cannot be resolved in either web.xml or the jar files deployed with this application

Can you help me ?

**Comment by kwon37xi** [comment]
This message means you did not put the jsp template inheritance  library  in your classpath.
Please check your project  dependency first.

**Comment by kwon37xi** [comment]
There's no more answer, so close this issue.
