### ISSUE TITLE
Trailing </layout> tag where </layout:extends> is preprocessed

### ISSUE THREAD

**Issue by derekvandaal** [kwon37xi/jsp-template-inheritance#6]
Hi, I'm getting an orphaned trailing </layout> tag in my resulting html

I believe it is produced by the closing </layout:extends> tag as per your example.

**Comment by kwon37xi** [comment]
I think you can change JSP Tag prefix to other than "layout".

Change the prefix attribute whatever you want in the following code.
```
<%@ taglib uri="http://kwonnam.pe.kr/jsp/template-inheritance" prefix="layout"%>
```

**Comment by kwon37xi** [comment]
Closing this issue, because there is no answer.
